quarkus:
  datasource:
    jdbc: false
    db-kind: oracle
    username: hreact
    password: hreact
    reactive:
      url: oracle:thin:@localhost:1521:hreact

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
