quarkus:
  datasource:
    jdbc: false
    db-kind: oracle
    username:
    password:
    reactive:
      url:

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
