quarkus:
  datasource:
    jdbc: false
    db-kind: oracle
    username: quarkus_test
    password: quarkus_test
    reactive:
      url: oracle:thin:@localhost:1521:quarkus_test

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
